### PR TITLE
Remove and disable app parts

### LINKED ISSUE #603: Remove or disable parts that does not work
Revise "typ hradla" and "typ FTA udalosti"

Image

Implement configuration parameter to hide FMEA functionality.

Image

Image

### PR DESCRIPTION
**Pull request by kostobog**
@blcham 
Fix #603

### CODE REVIEW

File: src/components/routes/AppRoutes.tsx [hunk 1]
```diff
@@ -56,11 +56,12 @@ const AppRoutes = () => {
...
       element: <FaultTreeDashboard />,
     },
-    {
+
+    !ENVVariable.DISABLE_FMEA && {
       path: ROUTES.FMEA,
       element: <FmeaOverview />,
     },
-    {
+    !ENVVariable.DISABLE_FMEA && {
```
Comment (blcham) [inline src/components/routes/AppRoutes.tsx:64]: I am not sure if this can work correctly:

image

**Review by blcham — CHANGES_REQUESTED** [review]
See my comment. Wouldn't be more readable/understandable to have:

ENVVariable.ENABLE_FMEA with default true?

**Review by blcham — APPROVED** [review]
