### PR TITLE
Fix blank page when selecting fault event with supertypes

### LINKED ISSUE #385: Screen goes blank when selecting fault event with supertypes in fault tree diagram

### PR DESCRIPTION
**Pull request by kostobog**
@blcham 
Fixes #385

### CODE REVIEW

File: src/components/dialog/faultEvent/FaultEventCreation.tsx [hunk 1]
```diff
@@ -63,6 +63,11 @@ const FaultEventCreation = ({ useFormMethods, isRootEvent, eventValue, isEditedE
   };
 
   function renderEventSelect() {
+    const supertype =
```
Comment (blcham) [inline src/components/dialog/faultEvent/FaultEventCreation.tsx:66]: This too complicated, how about:
```
const supertype = eventValue?.supertypes?.[0] || null;
const eventVal = supertype || eventValue;
const defaultValue = eventVal ? { name: eventVal.name, iri: eventVal.iri } : null;
```

It can be even simpler if you do not need null value, but undefined instead

Comment (blcham) [reply src/components/dialog/faultEvent/FaultEventCreation.tsx:66]: or optional array chaining see https://stackoverflow.com/questions/59623674/how-can-i-use-optional-chaining-with-arrays-and-functions

**Comment by kostobog** [comment]
Note that the last commit message [3b373bd](https://github.com/kbss-cvut/fta-fmea-ui/pull/386/commits/3b373bd5aa70ba7beafdd0f1eebeaebef91e7c79) 
- `[Fix #374] Call properly API to fetch reusable event type list when editing fault event` 
is incorrect. 

It should be the same as the previous one [ebc993f](https://github.com/kbss-cvut/fta-fmea-ui/pull/386/commits/ebc993f03c2fefe86dc4e9666c8663bfc83f4bec)
- `[Fixes #385] Fix error causing blank page when selecting fault event with supertype set by the user.`
