### PR TITLE
Fix minor issues

### LINKED ISSUE #676: Fix minor UI issues
## Issue 1
- [ ] Fix warning icon layout and error in console
Image
```
Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `ForwardRef(Tooltip2)`, expected a single ReactElement.
    at Tooltip2 (http://localhost:5173/node_modules/.vite/deps/chunk-YSMDCBEF.js?v=ed957962:720:17)
    at FaultTreeTableBody (http://localhost:5173/src/components/table/FaultTreeTableBody.tsx:31:31)
```

## Issue 2
- [ ] In navigation bar titles are not hidden when sidebar is collapsed 
Image

## Issue 3
- [ ] When user renames a fault tree to already existing fault tree name in `FaultTreeOverview`, UI updates name despite the error from server 

## Issue 4
- [ ] Updating Operational Data Filter in System does not work as expected:
  - Client reports error in `snackbar` and MOH is not update in UI despite server storing the new value

## Issue 5
- [ ] When deleting a system which is selected the selection is not cleared. 
This could be confusing as it will filter out all fault trees in the fault tree overview table.

Image

### PR DESCRIPTION
**Pull request by kostobog**
@blcham 
Fixes #676 
Fixes issues 1 - 5

### CODE REVIEW

File: src/components/dialog/faultTree/FaultTreeEditDialog.tsx [hunk 1]
```diff
@@ -38,17 +38,23 @@ const FaultTreeEditDialog = ({ open, handleCloseDialog, faultTree }: Props) => {
...
-    faultTree.name = values.faultTreeName;
     setIsProcessing(false);
     handleCloseDialog();
   };
 
   return (
     <Dialog open={open} onClose={handleCloseDialog} aria-labelledby="tree-edit-dialog-title" maxWidth="md" fullWidth>
       <DialogTitle id="tree-edit-dialog-title" onClose={handleCloseDialog}>
-        {t("renameFtaModal.title")}
+        {t("renameFtaModal.titl`e")}
```
Comment (blcham) [inline src/components/dialog/faultTree/FaultTreeEditDialog.tsx:57]: typo ?

**Review by blcham — CHANGES_REQUESTED** [review]
see my comment

File: src/components/dialog/faultTree/FaultTreeEditDialog.tsx (hunk 1 above)
Comment (kostobog) [reply src/components/dialog/faultTree/FaultTreeEditDialog.tsx]: @blcham 
Yes. fixed.
