### PR TITLE
Fix/494 small UI changes

### LINKED ISSUE #494: Small changes to fta-fmea-ui
- Replace ATA to SNS in UI
- show failure rate in exponential format

### PR DESCRIPTION
**Pull request by kostobog**
@blcham 
Fixes #494

### CODE REVIEW

File: src/components/editor/faultTree/menu/faultEvent/FaultEventMenu.tsx [hunk 1]
```diff
@@ -239,7 +239,11 @@ const FaultEventMenu = ({ shapeToolData, onEventUpdated, refreshTree, rootIri }:
         label={`${label}:`}
         className={selected ? classes.selected : classes.notSelected}
       />
-      <Typography className={outdated ? classes.outdated : classes.notEditableValue}>{rate}</Typography>
+      <Tooltip title={rate}>
```
Comment (blcham) [inline src/components/editor/faultTree/menu/faultEvent/FaultEventMenu.tsx:242]: @kostobog I do not understand this change :(

**Comment by blcham** [comment]
@Kasmadei have a peek
