### PR TITLE
Fix/354 filter reusable events based on global system selection

### LINKED ISSUE #354: Filter reusable fault events based on global system selection and fault tree

### PR DESCRIPTION
**Pull request by kostobog**
@blcham 
Fixes #354

### CODE REVIEW

File: src/hooks/useReusableFaultEvents.tsx [hunk 1]
```diff
@@ -18,16 +18,18 @@ export const useReusableFaultEvents = () => {
 
 interface Props extends ChildrenProps {
   treeUri?: string;
+  systemUri?: string;
 }
 
-export const FaultEventsReuseProvider = ({ children, treeUri }: Props) => {
+export const FaultEventsReuseProvider = ({ children, treeUri, systemUri }: Props) => {
```
Comment (blcham) [inline src/hooks/useReusableFaultEvents.tsx:24]: @kostobog  does it makes sense to rename it?

File: src/services/faultTreeService.tsx [hunk 2]
```diff
@@ -88,16 +88,31 @@ export const remove = async (faultTreeIri: string): Promise<void> => {
   }
 };
 
-export const getReusableEvents = async (faultTreeIri: string): Promise<FaultEvent[]> => {
+export const getRootReusableEvents = async (systemIri: string): Promise<FaultEvent[]> => {
```
Comment (blcham) [inline src/services/faultTreeService.tsx:91]: how about ReusableRootEvents ?

File: src/hooks/useReusableFaultEvents.tsx (hunk 1 above)
Comment (kostobog) [reply src/hooks/useReusableFaultEvents.tsx]: @blcham renamed to `ReusableFaultEventsProvider`
