### PR TITLE
Fix fault event menu form reset 

### LINKED ISSUE #446: Event field is populated with previous selection
When I create New fault tree, in field Event is previous selection. This also happens when adding new event to the tree.

- A/C:
- [x] previous selection is not shown when creating a new tree
- [x] previous selection is not shown when adding a new event to an existing tree

image

### PR DESCRIPTION
**Pull request by kostobog**
@blcham @LaChope 

It should fix #446
Reset form so that values correspond to selected event in fault tree
- show message if event in the fault tree is selected

### CODE REVIEW

**Comment by kostobog** [comment]
@blcham @LaChope 
Added additional fix on resetting the selected value in the autocomplete component.
I could not fix, resetting the autocomplete value when user selects a fault tree event for the first time after opening the fault tree editor.

  
image

image

File: src/components/editor/faultTree/menu/faultEvent/FaultEventMenu.tsx [hunk 1]
```diff
@@ -323,11 +323,10 @@ const FaultEventMenu = ({ selectedShapeToolData, onEventUpdated, refreshTree, ro
 
   return (
     <Box paddingLeft={2} marginRight={2}>
-      {shapeToolData && (
-        <ReusableFaultEventsProvider systemUri={selectedSystem?.iri}>
-          <FaultEventShapeToolPane data={shapeToolData} refreshTree={refreshTree} formMethods={formMethods} />
-        </ReusableFaultEventsProvider>
-      )}
+      <ReusableFaultEventsProvider systemUri={selectedSystem?.iri}>
```
Comment (blcham) [inline src/components/editor/faultTree/menu/faultEvent/FaultEventMenu.tsx:326]: just note you removed `shapeToolData &&`. Not sure why it was there in the first place.

**Review by blcham — APPROVED** [review]
LGTM, changes are quite complicated so i was not able to check/understand how it works, so @kostobog in case you are quite sure about fix, merge it, otherwise discuss

File: src/components/editor/faultTree/menu/faultEvent/FaultEventMenu.tsx (hunk 1 above)
Comment (kostobog) [reply src/components/editor/faultTree/menu/faultEvent/FaultEventMenu.tsx:326]: I also not sure why `shapeToolData &&` was there. The component `FaultEventShapeToolPane` is implemented so that it can handle if `shapeToolData` is null by  rendering a message that the there is no selection.

**Comment by kostobog** [comment]
@blcham 
I can merge but there is still issue the issue in the [comment](https://github.com/kbss-cvut/fta-fmea-ui/pull/586#issuecomment-2343793711) above.

**Comment by kostobog** [comment]
@blcham @LaChope 
The issue [comment](https://github.com/kbss-cvut/fta-fmea-ui/pull/586#issuecomment-2343793711) above is occurs with this PR. I managed to fixit in commit
[Set default value of ControlledAutocomplete in FaultEventCreation.](https://github.com/kbss-cvut/fta-fmea-ui/pull/586/commits/0fa866c9b99fdbcfe2d9cfc7a2e670c0399bf8a0)

Merging as I am not aware of any other issues.
